title: Levelyn
description: Music • Growth • Tech
url: "https://levelyn.blog"
baseurl: ""

# Theme
theme: null

# Top navigation
header_pages:
  - index.html
  - about.md

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
remote_theme: jekyll/minima

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

minima:
  social_links:
    - platform: github
      user_url: https://github.com/talemache
    - platform: linkedin
      user_url: https://www.linkedin.com/in/ryan-l-895b3b126/
    #- platform: x
      #user_url: https://x.com/<your-handle>

# Tidy up build
exclude:
  - README.md
  - README-RETRO.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
