title: Levelyn
description: Music • Growth • Tech
url: "https://levelyn.blog"
baseurl: ""

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10
paginate_path: "/page:num/"

minima:
  social_links:
    - platform: github
      user_url: https://github.com/<your-username>
    - platform: linkedin
      user_url: https://www.linkedin.com/in/<your-handle>/
    - platform: x
      user_url: https://x.com/<your-handle>
