title: Levelyn
description: ""
url: "https://levelyn.blog"
baseurl: ""

# Theme
theme: null

# # Top navigation
# header_pages:
#   - index.html
#   - about.md

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
remote_theme: jekyll/minima

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

minima:
  nav_pages:       # v3 replaces `header_pages`
    - index.html
    - about.md
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/talemache"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/ryan-l-895b3b126/"


# Tidy up build
exclude:
  - README.md
  - README-RETRO.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
 