title: Levelyn
description: "Music • Growth • Tech"
url: "https://levelyn.blog"
baseurl: ""

# Contact info
email: "ryan@levelyn.blog"

# Use no theme - we'll do custom layouts
theme: null

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Social links (for footer)
social_links:
  github: "https://github.com/talemache"
  linkedin: "https://www.linkedin.com/in/ryan-l-895b3b126/"

# Build settings
exclude:
  - README.md
  - README-RETRO.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor